SELECT * FROM ESTADO;

select NOME from estado WHERE ID = 1;

#SUBSELECT GERA UMA COLUNA - NO SUBSELECT SÓ PODE TRER UM UNICO VALOR DEPOIS DO SELECT, E TEM QUE TER UM WHERE PARA GERAR APENAS UMA COLUNA
SELECT ID
	,NOME
	,(select NOME from estado WHERE ID = ESTADO_ID) 'NOME do ESTADO'
FROM CIDADE;

# NAO DA CERTO ESSA SUBQUERY POIS TRARA MAIS DE UM NOME, AÍ TEMOS QUE USAR COUNT
SELECT
ID
,NOME
,SIGLA
,(SELECT NOME FROM CIDADE WHERE ESTADO_ID = ID)
FROM ESTADO;

#AGORA  QUERO TODAS AS CIDADES DO ESPIRITO SANTO - CONSULTA NA TABELA CIDADE (TABELA ANINHADA)

SELECT NOME FROM CIDADE WHERE ESTADO_ID = 2;



# AGORA COM COUNT - TAMBEM NAO DA CERTO, TEM QUE DIGITAR NOME DAS TABELAS(COLOQUEI O E DE ESTADO E C DE CIDADE
SELECT
E.ID
,E.NOME
,E.SIGLA
,(SELECT COUNT(C.NOME) FROM CIDADE C WHERE C.ESTADO_ID = E.ID)
FROM ESTADO E;


# AGORA COM GROUP_CONCAT - TAMBEM NAO DA CERTO, TEM QUE DIGITAR NOME DAS TABELAS(COLOQUEI O E DE ESTADO E C DE CIDADE
SELECT
E.ID
,E.NOME
,E.SIGLA
,(SELECT GROUP_CONCAT(C.NOME) FROM CIDADE C WHERE C.ESTADO_ID = E.ID)
FROM ESTADO E;

#AGORA NA CLAUSULA FROM - PARA GERAR UMA OUTRA TABELA
SELECT MINHA_TABELA.NOME 'NOMEZINHO DO ESTADO' 
FROM (select * FROM ESTADO WHERE ID>1) MINHA_TABELA;




SELECT MEU_RELATORIO.NOME_ESTADO, QTDDE, NOMES
FROM
		(SELECT
		E.ID
		,E.NOME NOME_ESTADO
		,E.SIGLA
        ,(SELECT COUNT(C.NOME) FROM CIDADE C WHERE C.ESTADO_ID = E.ID) 'QTDDE'
		,(SELECT GROUP_CONCAT(C.NOME) FROM CIDADE C WHERE C.ESTADO_ID = E.ID)'NOMES'
		FROM ESTADO E) MEU_RELATORIO;
        
#SUBSELECT EM WHERE

SELECT * FROM EMPRESA



