SELECT * FROM tbproduto WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;
SELECT *FROM tbcliente WHERE IDADE >= 18 AND IDADE <=42 AND SEXO = 'M' AND CIDADE = 'São Paulo';
SELECT *FROM tbcliente WHERE IDADE >= 18 AND IDADE <=42 AND SEXO = 'M' AND (CIDADE = 'São Paulo' OR CIDADE ='Rio de Janeiro');