SELECT *FROM tbcliente;

SELECT *FROM tbcliente WHERE IDADE = 25;

SELECT *FROM tbcliente WHERE IDADE < 25;

SELECT *FROM tbcliente WHERE IDADE <= 25;

SELECT *FROM tbcliente WHERE IDADE <> 25 AND IDADE <> 22;

SELECT * FROM tbproduto WHERE PRECO_LISTA BETWEEN 16.07 AND 16.00;

SELECT NOME FROM tabela_de_vendedores WHERE PERCENTUAL_COMISSAO > 10.00;



