CREATE DATABASE mao_na_massa;

USE mao_na_massa;

CREATE TABLE Estado (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    SIGLA VARCHAR(4) NOT NULL
);

CREATE TABLE Cidade (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    ESTADO_ID INT NOT NULL,
    constraint PK_CIDADE primary key (ID),
    constraint FK_CIDADE_ESTADO foreign key (ESTADO_ID) references ESTADO (ID),
    constraint CIDADE_UNICA unique(NOME, ESTADO_ID)
);

CREATE TABLE Empresa (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(15) NOT null,
    CIDADE_ID INT NOT null,
    constraint PK_CLIENTE primary key (ID),
    constraint FK_CLIENTE_CIDADE foreign key (CIDADE_ID) references CIDADE (ID)
);

INSERT INTO ESTADO (NOME, SIGLA) VALUES("SÃO PAULO","SP");
INSERT INTO ESTADO (NOME, SIGLA) VALUES("ESPIRITO SANTO","ES");
INSERT INTO ESTADO (NOME, SIGLA) VALUES("RIO GRANDE DO SUL","RS");

INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES("Mairipora", 1);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES("Vila Velha", 2);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES("Santa Clara ", 3);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES("Santos", 1);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES("Santo André", 1);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES("Gonçalves Bento", 3);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES("Ponta Média", 2);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES("Guararema", 1);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES("Ilha Bela", 1);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES("Galapagus", 2);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES("Correia", 2);


