SELECT EMPRESAS.NOME AS NOME_EMPRESA, MATRIZ.CNPJ_MATRIZ, MATRIZ.NOME AS NOME_DA_MATRIZ, MATRIZ.FATURAMENTO AS FATURAMENTO_MATRIZ
FROM EMPRESAS
JOIN MATRIZ ON EMPRESAS.MATRIZ_ID = MATRIZ.ID
WHERE EMPRESAS.NOME = 'DB 77';

CREATE TABLE faturamento_matriz AS
SELECT
    EMPRESAS.NOME AS NomeEmpresa,
    MATRIZ.CNPJ_MATRIZ,
    MATRIZ.FATURAMENTO AS Faturamento_Matriz
FROM EMPRESAS
JOIN MATRIZ ON EMPRESAS.MATRIZ_ID = MATRIZ.ID;

SELECT * FROM FATURAMENTO_MATRIZ;

UPDATE EMPRESAS
SET MATRIZ_ID = 1
WHERE CNPJ = '123434/0008-23' OR CNPJ = '123434/0007-25';


UPDATE EMPRESAS
SET MATRIZ_ID = 1
WHERE CNPJ = '123434/0008-23';

UPDATE EMPRESAS
SET MATRIZ_ID = 1
WHERE CNPJ = '123434/0007-25';


SELECT * FROM EMPRESAS;

SELECT 
	NOME
    ,CNPJ
FROM
	EMPRESAS
    WHERE MATRIZ_ID = 1;

CREATE TABLE outra_tabela AS
SELECT
    EMPRESAS.NOME AS NomeEmpresa,
    EMPRESAS.CNPJ AS CNPJ_Empresa,
    (SELECT CNPJ_MATRIZ FROM MATRIZ WHERE MATRIZ.ID = EMPRESAS.MATRIZ_ID) AS CNPJMatriz,
    (SELECT FATURAMENTO FROM MATRIZ WHERE MATRIZ.ID = EMPRESAS.MATRIZ_ID) AS FaturamentoMatriz
FROM EMPRESAS;

SELECT * FROM outra_tabela;

CREATE TABLE faturamento_da_matriz AS
SELECT
    EMPRESAS.NOME AS NomeEmpresa,
    MATRIZ.CNPJ_MATRIZ,
    MATRIZ.FATURAMENTO AS Faturamento_Matriz
FROM EMPRESAS
JOIN MATRIZ ON EMPRESAS.MATRIZ_ID = MATRIZ.ID;

SELECT * FROM FATURAMENTO_da_MATRIZ;

FLUSH TABLES;

SELECT
    EMPRESAS.NOME AS NomeEmpresa,
    MATRIZ.CNPJ_MATRIZ,
    MATRIZ.FATURAMENTO AS FaturamentoMatriz,
    CASE WHEN EMPRESAS.CNPJ = MATRIZ.CNPJ_MATRIZ THEN 'TRUE' ELSE 'FALSE' END AS CNPJ_Igual_Matriz
FROM EMPRESAS
JOIN MATRIZ ON EMPRESAS.MATRIZ_ID = MATRIZ.ID;