USE sucos;

ALTER TABLE tbcliente ADD PRIMARY KEY (CPF);

ALTER TABLE tbcliente ADD COLUMN (DATA_NASCIMENTO DATE);

INSERT INTO tbcliente (
CPF, NOME, ENDERECO1, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO)
VALUES ('36827587153','Sandro Ricardo de Almeida','Rua Ganges, 134','Vila do Carmo','Pirapora','MG','65253695',34,'M',456.00,32.65,0, '1988-08-25');

SELECT * FROM tbcliente;